### ISSUE TITLE
11: MLP RElu vs MLP  sigmoid

### ISSUE THREAD

**Issue by pmags** [pmags/fcup_ml_modelCompare#5]

**Comment by Martaprf** [comment]
Não sei se me poderás ajudar com isto, mas é que eu não estou a conseguir fazer este porque usando o nnet eu consigo por como parametro a função de activação "relu", mas não consigo colocar a sigmoid.

**Comment by pmags** [comment]
@Martaprf a sigmoid é um caso especial da logistica  que no caso de parsnipt em mlp deverá ser "linear" com método classificação uma vez que o modelo linear para classificação é o logit. 

Infelizmente gostava de encontrar alguma documentação que demonstrasse que eu estou certo 😞. Mas arriscamos por ai.
